cc_library(
    name = "vector_buffer",
    srcs = [
        "vector_buffer.cc",
    ],
    hdrs = [
        "vector_buffer.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":buffer",
    ],
)

cc_library(
    name = "buffer",
    hdrs = [
        "buffer.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
