cc_library(
    name = "editor",
    srcs = [
        "editor.cc",
    ],
    hdrs = [
        "editor.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//buffer",
        "//buffer:vector_buffer",
        "//view",
        "//view:command_line",
        "//view:status_line",
    ],
)
