cc_library(
    name = "raw_term",
    srcs = [
        "raw_term.cc",
    ],
    hdrs = [
        "raw_term.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":keyboard",
    ],
)

cc_library(
    name = "keyboard",
    hdrs = [
        "keyboard.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
