cc_library(
    name = "raw_terminal",
    srcs = [
        "raw_terminal.cc",
    ],
    hdrs = [
        "raw_terminal.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":keyboard",
        "//view:viewport",
    ],
)

cc_library(
    name = "keyboard",
    hdrs = [
        "keyboard.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
